"""
Common database queries.

Anything more than a one-liner SELECT lives here as a typed function.
Keeps query logic out of business logic modules.

TODO (Claude Code):
    async def get_recent_candles(symbol: str, tf: str, n: int) -> list[Candle]: ...
    async def get_current_account() -> AccountSnapshot: ...
    async def get_open_positions() -> list[Position]: ...
    async def get_today_trades() -> list[Trade]: ...
    async def get_pnl_stats() -> PnLStats: ...
    async def get_upcoming_events(within_minutes: int) -> list[Event]: ...
"""
from __future__ import annotations
